//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dashboard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dashboard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Dashboard", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آموزش.
        /// </summary>
        internal static string amoozesh {
            get {
                return ResourceManager.GetString("amoozesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه هفتگی.
        /// </summary>
        internal static string barname_haftegi {
            get {
                return ResourceManager.GetString("barname_haftegi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانه                                           .
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکالیف.
        /// </summary>
        internal static string homework {
            get {
                return ResourceManager.GetString("homework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارنامه ماهانه.
        /// </summary>
        internal static string karname_mahane {
            get {
                return ResourceManager.GetString("karname_mahane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارنامه سالانه.
        /// </summary>
        internal static string karname_salane {
            get {
                return ResourceManager.GetString("karname_salane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارتابل.
        /// </summary>
        internal static string kartabl {
            get {
                return ResourceManager.GetString("kartabl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخبار.
        /// </summary>
        internal static string news {
            get {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمودار پیشرفت تحصیلی.
        /// </summary>
        internal static string nmoodar {
            get {
                return ResourceManager.GetString("nmoodar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمرات.
        /// </summary>
        internal static string nomarat {
            get {
                return ResourceManager.GetString("nomarat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش مشخصات.
        /// </summary>
        internal static string virayesh_mshakhasat {
            get {
                return ResourceManager.GetString("virayesh_mshakhasat", resourceCulture);
            }
        }
    }
}
