//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dashboard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dashboard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Dashboard", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس محل سکونت.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آموزش.
        /// </summary>
        internal static string amoozesh {
            get {
                return ResourceManager.GetString("amoozesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه هفتگی.
        /// </summary>
        internal static string barname_haftegi {
            get {
                return ResourceManager.GetString("barname_haftegi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال تولد.
        /// </summary>
        internal static string birthday {
            get {
                return ResourceManager.GetString("birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر رمز عبور.
        /// </summary>
        internal static string change_password {
            get {
                return ResourceManager.GetString("change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر عکس پروفایل.
        /// </summary>
        internal static string change_picture {
            get {
                return ResourceManager.GetString("change_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        internal static string codemelli {
            get {
                return ResourceManager.GetString("codemelli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور فعلی.
        /// </summary>
        internal static string c_password {
            get {
                return ResourceManager.GetString("c_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        internal static string edite {
            get {
                return ResourceManager.GetString("edite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست الکترونیک.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        internal static string family {
            get {
                return ResourceManager.GetString("family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پدر.
        /// </summary>
        internal static string father_name {
            get {
                return ResourceManager.GetString("father_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانه                                           .
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکالیف.
        /// </summary>
        internal static string homework {
            get {
                return ResourceManager.GetString("homework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخچه تکالیف.
        /// </summary>
        internal static string homework_history {
            get {
                return ResourceManager.GetString("homework_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل تصویر.
        /// </summary>
        internal static string img_file {
            get {
                return ResourceManager.GetString("img_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارنامه ماهانه.
        /// </summary>
        internal static string karname_mahane {
            get {
                return ResourceManager.GetString("karname_mahane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارنامه سالانه.
        /// </summary>
        internal static string karname_salane {
            get {
                return ResourceManager.GetString("karname_salane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارتابل شخصی.
        /// </summary>
        internal static string kartabl {
            get {
                return ResourceManager.GetString("kartabl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقطع تحصیلی.
        /// </summary>
        internal static string maghta {
            get {
                return ResourceManager.GetString("maghta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل.
        /// </summary>
        internal static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخبار.
        /// </summary>
        internal static string news {
            get {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمودار پیشرفت تحصیلی.
        /// </summary>
        internal static string nmoodar {
            get {
                return ResourceManager.GetString("nmoodar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمرات.
        /// </summary>
        internal static string nomarat {
            get {
                return ResourceManager.GetString("nomarat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور جدید.
        /// </summary>
        internal static string n_password {
            get {
                return ResourceManager.GetString("n_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت ها.
        /// </summary>
        internal static string payments {
            get {
                return ResourceManager.GetString("payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی محل سکونت.
        /// </summary>
        internal static string postal_code {
            get {
                return ResourceManager.GetString("postal_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته تحصیلی.
        /// </summary>
        internal static string reshte_tahsili {
            get {
                return ResourceManager.GetString("reshte_tahsili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت.
        /// </summary>
        internal static string sabt {
            get {
                return ResourceManager.GetString("sabt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهریه.
        /// </summary>
        internal static string salary {
            get {
                return ResourceManager.GetString("salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت شهریه.
        /// </summary>
        internal static string salary_payment {
            get {
                return ResourceManager.GetString("salary_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب تصویر.
        /// </summary>
        internal static string select_img {
            get {
                return ResourceManager.GetString("select_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره دانش آموزی.
        /// </summary>
        internal static string shomare_daneshamozi {
            get {
                return ResourceManager.GetString("shomare_daneshamozi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن ثابت محل سکونت.
        /// </summary>
        internal static string telephon_sabet {
            get {
                return ResourceManager.GetString("telephon_sabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار رمز عبور جدید.
        /// </summary>
        internal static string tn_password {
            get {
                return ResourceManager.GetString("tn_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش مشخصات.
        /// </summary>
        internal static string virayesh_mshakhasat {
            get {
                return ResourceManager.GetString("virayesh_mshakhasat", resourceCulture);
            }
        }
    }
}
