//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Father
    {
        public Father()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int FatherID { get; set; }
        public int NationalCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PersonalCode { get; set; }
        public string Job { get; set; }
        public string MobileNumber { get; set; }
        public string WorkPhone { get; set; }
        public string Education { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
