//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public Grade()
        {
            this.LessonGroups = new HashSet<LessonGroup>();
            this.Students = new HashSet<Student>();
        }
    
        public int GradeID { get; set; }
        public string GradeTitle { get; set; }
    
        public virtual ICollection<LessonGroup> LessonGroups { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
