//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JavabeTamrin
    {
        public int JavabID { get; set; }
        public Nullable<int> TamrinID { get; set; }
        public Nullable<int> OzviatID { get; set; }
        public string FilePath { get; set; }
        public string Description { get; set; }
        public string SendingTime { get; set; }
        public string SendingDate { get; set; }
    
        public virtual Ozviat Ozviat { get; set; }
        public virtual Tamarin Tamarin { get; set; }
    }
}
