//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonGroup
    {
        public LessonGroup()
        {
            this.Ozviats = new HashSet<Ozviat>();
            this.Tamarins = new HashSet<Tamarin>();
        }
    
        public int LGID { get; set; }
        public string Class { get; set; }
        public Nullable<int> LessonID { get; set; }
        public string TeacherCode { get; set; }
        public Nullable<int> GradeID { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Time { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual Karmand Karmand { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual ICollection<Ozviat> Ozviats { get; set; }
        public virtual ICollection<Tamarin> Tamarins { get; set; }
    }
}
