//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public Lesson()
        {
            this.LessonGroups = new HashSet<LessonGroup>();
        }
    
        public int LessonID { get; set; }
        public string LessonTitle { get; set; }
        public Nullable<int> Unit { get; set; }
    
        public virtual ICollection<LessonGroup> LessonGroups { get; set; }
    }
}
