//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ozviat
    {
        public Ozviat()
        {
            this.JavabeTamrins = new HashSet<JavabeTamrin>();
            this.Nomarats = new HashSet<Nomarat>();
            this.Presences = new HashSet<Presence>();
        }
    
        public int OzviatID { get; set; }
        public Nullable<int> LGID { get; set; }
        public Nullable<long> StudentCode { get; set; }
    
        public virtual ICollection<JavabeTamrin> JavabeTamrins { get; set; }
        public virtual LessonGroup LessonGroup { get; set; }
        public virtual ICollection<Nomarat> Nomarats { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<Presence> Presences { get; set; }
    }
}
