//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBarname
    {
        public string Class { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Time { get; set; }
        public string StudentCode { get; set; }
        public string LessonTitle { get; set; }
        public int OzviatID { get; set; }
    }
}
