//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vJTamrin
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long StudentCode { get; set; }
        public string FilePath { get; set; }
        public string Description { get; set; }
        public int JavabID { get; set; }
        public string TeacherFName { get; set; }
        public string TeacherLName { get; set; }
        public string PersonalCode { get; set; }
        public int TamrinID { get; set; }
        public string TamrinTitle { get; set; }
        public string StartDate { get; set; }
        public string ExpirationDate { get; set; }
        public string LessonTitle { get; set; }
        public string SendingTime { get; set; }
        public string SendingDate { get; set; }
    }
}
