//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLessonGroup
    {
        public int LGID { get; set; }
        public string Class { get; set; }
        public string LessonTitle { get; set; }
        public Nullable<int> Unit { get; set; }
        public int EID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string BirthDate { get; set; }
        public string Mobile { get; set; }
        public string PhoneNumber { get; set; }
        public string PesonalCode { get; set; }
        public string Type { get; set; }
        public string GradeTitle { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Time { get; set; }
    }
}
