//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPresence
    {
        public long StudentCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> FatherID { get; set; }
        public string ParentUser { get; set; }
        public string ParentPass { get; set; }
        public string Class { get; set; }
        public string Date { get; set; }
        public Nullable<bool> Status { get; set; }
        public string LessonTitle { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<bool> isMovajjah { get; set; }
        public string Description { get; set; }
    }
}
