//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vStudent
    {
        public int StuID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string StudentCode { get; set; }
        public Nullable<int> SGarde { get; set; }
        public string NationalCode { get; set; }
        public string IdentityCode { get; set; }
        public string BirthDate { get; set; }
        public string BirthLocation { get; set; }
        public string Address { get; set; }
        public string RegisterLocation { get; set; }
        public string PhoneNumber { get; set; }
        public string PreviousSchool { get; set; }
        public string ArgentPhoneNumber { get; set; }
        public string Ilneses { get; set; }
        public Nullable<bool> Hand { get; set; }
        public string Sarparast { get; set; }
        public string Image { get; set; }
        public string CodeRahgiri { get; set; }
        public string Description { get; set; }
        public int FathersNationalCode { get; set; }
        public string FathersFirstName { get; set; }
        public string FathersLastName { get; set; }
        public string FathersPersonalCode { get; set; }
        public string FathersJob { get; set; }
        public string FathersMobileNumber { get; set; }
        public string FathersWorkPhone { get; set; }
        public string FathersEducation { get; set; }
        public int MothersNationalCode { get; set; }
        public string MothersFirstName { get; set; }
        public string MothersLastName { get; set; }
        public string MothersPersonalCode { get; set; }
        public string MothersJob { get; set; }
        public string MothersMobileNumber { get; set; }
        public string MothersWorkPhone { get; set; }
        public string MothersEducation { get; set; }
        public Nullable<int> CGrade { get; set; }
        public string GradeTitle { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ParentUser { get; set; }
        public string ParentPass { get; set; }
        public string MobileNumber { get; set; }
        public string ZipCode { get; set; }
        public string Email { get; set; }
    }
}
